# Generated by Django 3.1.1 on 2021-06-04 03:01

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bit_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(default='', max_length=20)),
                ('json_payload', jsonfield.fields.JSONField(default=dict)),
                ('machine', models.IntegerField(choices=[(0, 'Dovetailmachine'), (1, 'Drilldowelmachine')])),
                ('bit_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bit_profiles.bitprofile')),
            ],
        ),
    ]
