# Generated by Django 3.1.1 on 2021-07-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joint_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinprofile',
            name='profile_name',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
