# Generated by Django 3.1.1 on 2021-05-27 23:01

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('joint_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinprofile',
            name='json_payload',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
