# Generated by Django 3.1.1 on 2021-12-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joint_profiles', '0002_auto_20210702_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinprofile',
            name='machine',
            field=models.IntegerField(choices=[(0, 'Dovetailmachine'), (1, 'Drilldowelmachine'), (2, 'Sandingmachine')]),
        ),
    ]
