# Generated by Django 3.1.1 on 2021-05-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joint_profiles', '0003_joinprofile_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinprofile',
            name='machine',
            field=models.IntegerField(choices=[(0, 'Dovetailmachine'), (1, 'Drilldowelmachine')]),
        ),
    ]
