# Generated by Django 3.1.1 on 2021-12-01 22:33

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(default='', max_length=20, unique=True)),
                ('json_payload', jsonfield.fields.JSONField(default=dict)),
                ('machine', models.IntegerField(choices=[(0, 'Dovetailmachine'), (1, 'Drilldowelmachine')])),
            ],
        ),
    ]
