# Generated by Django 3.1.1 on 2021-12-03 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanding_machine', '0002_sandpaper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sandpaper',
            old_name='sand_paper_number',
            new_name='profile_name',
        ),
    ]
