# Generated by Django 3.1.1 on 2021-12-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanding_machine', '0003_auto_20211203_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partprofile',
            name='machine',
            field=models.IntegerField(choices=[(0, 'Dovetailmachine'), (1, 'Drilldowelmachine'), (2, 'Sandingmachine')]),
        ),
        migrations.AlterField(
            model_name='sandpaper',
            name='machine',
            field=models.IntegerField(choices=[(0, 'Dovetailmachine'), (1, 'Drilldowelmachine'), (2, 'Sandingmachine')]),
        ),
    ]
