# Generated by Django 3.1.1 on 2021-12-24 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanding_machine', '0004_auto_20211224_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sander',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('x_length', models.FloatField(default=0)),
                ('y_length', models.FloatField(default=0)),
                ('is_square', models.BooleanField(default=False)),
                ('is_fine', models.BooleanField(default=False)),
                ('installed_sandpaper', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sanding_machine.sandpaper')),
            ],
        ),
    ]
