# Generated by Django 3.1.1 on 2021-12-24 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanding_machine', '0005_sander'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sander',
            name='installed_sandpaper',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sanding_machine.sandpaper'),
        ),
        migrations.AlterField(
            model_name='sander',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
