# Generated by Django 3.1.1 on 2021-12-25 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanding_machine', '0007_doorstyle'),
    ]

    operations = [
        migrations.CreateModel(
            name='SandingProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(default='', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SandingProgramPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contain_frames', models.BooleanField(default=False)),
                ('contain_panels', models.BooleanField(default=False)),
                ('is_entire_panel', models.BooleanField(null=True)),
                ('contain_slabs', models.BooleanField(default=False)),
                ('make_extra_pass_around_perimeter', models.BooleanField(default=False)),
                ('overlap_value', models.IntegerField()),
                ('pressure_value', models.IntegerField()),
                ('speed_value', models.IntegerField()),
                ('hangover_value', models.IntegerField()),
                ('is_temp', models.BooleanField(default=True)),
                ('sander', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sanding_machine.sander')),
                ('sanding_program', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sanding_machine.sandingprogram')),
            ],
        ),
    ]
