# Generated by Django 3.1.1 on 2021-12-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanding_machine', '0008_sandingprogram_sandingprogrampass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandingprogrampass',
            name='hangover_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sandingprogrampass',
            name='overlap_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sandingprogrampass',
            name='pressure_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sandingprogrampass',
            name='speed_value',
            field=models.IntegerField(null=True),
        ),
    ]
