# Generated by Django 3.1.1 on 2021-12-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanding_machine', '0009_auto_20211225_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sandingprogram',
            old_name='program_name',
            new_name='name',
        ),
    ]
