# Generated by Django 3.0.1 on 2022-03-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanding_machine', '0010_auto_20211225_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandingprogrampass',
            name='pass_order',
            field=models.IntegerField(default=0),
        ),
    ]
