# Generated by Django 3.0 on 2023-01-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanding_machine', '0011_sandingprogrampass_pass_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorstyle',
            name='tool_id',
            field=models.TextField(default=''),
        ),
    ]
