# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'custom_widgets/numpad_widget.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_numpad(object):
    def setupUi(self, numpad):
        numpad.setObjectName("numpad")
        numpad.resize(400, 290)
        numpad.setMaximumSize(QtCore.QSize(400, 290))
        numpad.setStyleSheet("QWidget\n"
"{text-transform: uppercase;\n"
" font-family:\"Helvetica\";\n"
" font-size:18pt;\n"
" font-weight:bold;\n"
"}")
        numpad.setSizeGripEnabled(False)
        numpad.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(numpad)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(numpad)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.min_val = QtWidgets.QLabel(numpad)
        self.min_val.setObjectName("min_val")
        self.horizontalLayout.addWidget(self.min_val)
        self.min_unit = QtWidgets.QLabel(numpad)
        self.min_unit.setObjectName("min_unit")
        self.horizontalLayout.addWidget(self.min_unit)
        spacerItem = QtWidgets.QSpacerItem(27, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(numpad)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.max_val = QtWidgets.QLabel(numpad)
        self.max_val.setObjectName("max_val")
        self.horizontalLayout.addWidget(self.max_val)
        self.max_unit = QtWidgets.QLabel(numpad)
        self.max_unit.setObjectName("max_unit")
        self.horizontalLayout.addWidget(self.max_unit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.disp_pannel = QtWidgets.QLabel(numpad)
        self.disp_pannel.setMinimumSize(QtCore.QSize(0, 60))
        self.disp_pannel.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.disp_pannel.setObjectName("disp_pannel")
        self.horizontalLayout_2.addWidget(self.disp_pannel)
        self.disp_unit = QtWidgets.QLabel(numpad)
        self.disp_unit.setObjectName("disp_unit")
        self.horizontalLayout_2.addWidget(self.disp_unit)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_7 = QtWidgets.QPushButton(numpad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_7.sizePolicy().hasHeightForWidth())
        self.btn_7.setSizePolicy(sizePolicy)
        self.btn_7.setObjectName("btn_7")
        self.gridLayout.addWidget(self.btn_7, 0, 0, 1, 1)
        self.btn_8 = QtWidgets.QPushButton(numpad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_8.sizePolicy().hasHeightForWidth())
        self.btn_8.setSizePolicy(sizePolicy)
        self.btn_8.setObjectName("btn_8")
        self.gridLayout.addWidget(self.btn_8, 0, 1, 1, 1)
        self.btn_9 = QtWidgets.QPushButton(numpad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_9.sizePolicy().hasHeightForWidth())
        self.btn_9.setSizePolicy(sizePolicy)
        self.btn_9.setObjectName("btn_9")
        self.gridLayout.addWidget(self.btn_9, 0, 2, 1, 1)
        self.btn_in = QtWidgets.QPushButton(numpad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_in.sizePolicy().hasHeightForWidth())
        self.btn_in.setSizePolicy(sizePolicy)
        self.btn_in.setObjectName("btn_in")
        self.gridLayout.addWidget(self.btn_in, 0, 3, 1, 1)
        self.btn_4 = QtWidgets.QPushButton(numpad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_4.sizePolicy().hasHeightForWidth())
        self.btn_4.setSizePolicy(sizePolicy)
        self.btn_4.setObjectName("btn_4")
        self.gridLayout.addWidget(self.btn_4, 1, 0, 1, 1)
        self.btn_5 = QtWidgets.QPushButton(numpad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_5.sizePolicy().hasHeightForWidth())
        self.btn_5.setSizePolicy(sizePolicy)
        self.btn_5.setObjectName("btn_5")
        self.gridLayout.addWidget(self.btn_5, 1, 1, 1, 1)
        self.btn_6 = QtWidgets.QPushButton(numpad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_6.sizePolicy().hasHeightForWidth())
        self.btn_6.setSizePolicy(sizePolicy)
        self.btn_6.setObjectName("btn_6")
        self.gridLayout.addWidget(self.btn_6, 1, 2, 1, 1)
        self.btn_clear = QtWidgets.QPushButton(numpad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_clear.sizePolicy().hasHeightForWidth())
        self.btn_clear.setSizePolicy(sizePolicy)
        self.btn_clear.setObjectName("btn_clear")
        self.gridLayout.addWidget(self.btn_clear, 1, 3, 1, 1)
        self.btn_1 = QtWidgets.QPushButton(numpad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_1.sizePolicy().hasHeightForWidth())
        self.btn_1.setSizePolicy(sizePolicy)
        self.btn_1.setObjectName("btn_1")
        self.gridLayout.addWidget(self.btn_1, 2, 0, 1, 1)
        self.btn_2 = QtWidgets.QPushButton(numpad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_2.sizePolicy().hasHeightForWidth())
        self.btn_2.setSizePolicy(sizePolicy)
        self.btn_2.setObjectName("btn_2")
        self.gridLayout.addWidget(self.btn_2, 2, 1, 1, 1)
        self.btn_3 = QtWidgets.QPushButton(numpad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_3.sizePolicy().hasHeightForWidth())
        self.btn_3.setSizePolicy(sizePolicy)
        self.btn_3.setObjectName("btn_3")
        self.gridLayout.addWidget(self.btn_3, 2, 2, 1, 1)
        self.btn_reset = QtWidgets.QPushButton(numpad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_reset.sizePolicy().hasHeightForWidth())
        self.btn_reset.setSizePolicy(sizePolicy)
        self.btn_reset.setObjectName("btn_reset")
        self.gridLayout.addWidget(self.btn_reset, 2, 3, 1, 1)
        self.btn_0 = QtWidgets.QPushButton(numpad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_0.sizePolicy().hasHeightForWidth())
        self.btn_0.setSizePolicy(sizePolicy)
        self.btn_0.setObjectName("btn_0")
        self.gridLayout.addWidget(self.btn_0, 3, 0, 1, 2)
        self.btn_dot = QtWidgets.QPushButton(numpad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_dot.sizePolicy().hasHeightForWidth())
        self.btn_dot.setSizePolicy(sizePolicy)
        self.btn_dot.setObjectName("btn_dot")
        self.gridLayout.addWidget(self.btn_dot, 3, 2, 1, 1)
        self.btn_save = QtWidgets.QPushButton(numpad)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_save.sizePolicy().hasHeightForWidth())
        self.btn_save.setSizePolicy(sizePolicy)
        self.btn_save.setObjectName("btn_save")
        self.gridLayout.addWidget(self.btn_save, 3, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(numpad)
        QtCore.QMetaObject.connectSlotsByName(numpad)

    def retranslateUi(self, numpad):
        _translate = QtCore.QCoreApplication.translate
        numpad.setWindowTitle(_translate("numpad", "Dialog"))
        self.label.setText(_translate("numpad", "min:"))
        self.min_val.setText(_translate("numpad", "18.2"))
        self.min_unit.setText(_translate("numpad", "mm"))
        self.label_2.setText(_translate("numpad", "max:"))
        self.max_val.setText(_translate("numpad", "18.2"))
        self.max_unit.setText(_translate("numpad", "mm"))
        self.disp_pannel.setText(_translate("numpad", "131556.5"))
        self.disp_unit.setText(_translate("numpad", "MM"))
        self.btn_7.setText(_translate("numpad", "7"))
        self.btn_8.setText(_translate("numpad", "8"))
        self.btn_9.setText(_translate("numpad", "9"))
        self.btn_in.setText(_translate("numpad", "\""))
        self.btn_4.setText(_translate("numpad", "4"))
        self.btn_5.setText(_translate("numpad", "5"))
        self.btn_6.setText(_translate("numpad", "6"))
        self.btn_clear.setText(_translate("numpad", "C"))
        self.btn_1.setText(_translate("numpad", "1"))
        self.btn_2.setText(_translate("numpad", "2"))
        self.btn_3.setText(_translate("numpad", "3"))
        self.btn_reset.setText(_translate("numpad", "R"))
        self.btn_0.setText(_translate("numpad", "0"))
        self.btn_dot.setText(_translate("numpad", "."))
        self.btn_save.setText(_translate("numpad", "SAVE"))
