from .joint_profiles.joint_profile_manager import JointProfilesPageManager
from .dowel_profile.dowel_profile_manager import DowelProfileManager
from .camera_page_manager import DovetailCameraPageManager
