# Generated by Django 3.1.1 on 2020-11-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_productivity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_size', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
