# Generated by Django 3.1.1 on 2020-11-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_productivity', '0002_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='mode',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='part',
            name='profile_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
