# Generated by Django 3.1.1 on 2020-11-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_productivity', '0003_auto_20201101_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='direction',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='part',
            name='mode',
            field=models.CharField(default='', max_length=20),
        ),
    ]
