# Generated by Django 3.1.1 on 2020-11-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_productivity', '0004_auto_20201101_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxisMotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_axis', models.FloatField(default=0)),
                ('y_axis', models.FloatField(default=0)),
                ('z_axis', models.FloatField(default=0)),
                ('a_axis', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
