# Generated by Django 3.1.1 on 2020-11-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_productivity', '0006_auto_20201111_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axismotion',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dowels',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='holes',
            name='date',
            field=models.DateField(),
        ),
    ]
