# Generated by Django 3.1.1 on 2020-11-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_productivity', '0008_maintainance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintainance',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
