# Generated by Django 3.1.1 on 2020-11-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_productivity', '0009_auto_20201112_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintainance',
            name='date',
            field=models.DateField(),
        ),
    ]
