# Generated by Django 3.1.1 on 2020-11-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_productivity', '0010_auto_20201112_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintainance',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
