# Generated by Django 3.1.1 on 2021-05-28 21:04

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DowelProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(default='', max_length=20)),
                ('default_prams_json', jsonfield.fields.JSONField(default=dict)),
                ('machine', models.IntegerField(choices=[(0, 'Dovetailmachine'), (1, 'Drilldowelmachine')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DowelJoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prams_json', jsonfield.fields.JSONField(default=dict)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dowel_profiles.dowelprofile')),
            ],
        ),
    ]
